### ISSUE TITLE
Expected run time of an experiment

### ISSUE THREAD

**Issue by Ushk** [niopeng/HyperRIM#2]
Hi - as with the other issue, thank you for releasing the code - I found it well written and easy to understand/extend. 

I'd just like to ask that in your experience, what is the expected run time of an SR experiment, and what hardware you used to run your experiments? I'm not asking from an environment perspective, but from a "How computationally expensive is this model?" perspective.

**Comment by niopeng** [comment]
Hi, thank you for the feedback! In terms of computational costs, training one [pretrained SR models](https://github.com/niopeng/HyperRIM/tree/main/experiments/pretrained_models) took around 100hrs for me. The setup consists of a 32GB NVIDIA V100 GPU, 50GB RAM and 6-core CPU.

**Comment by Ushk** [comment]
Thanks for the comment, that's really helpful :)
